### ISSUE TITLE
tried to invite someone to Invenbin and got an error

### ISSUE THREAD

**Issue by bperreault** [prasso/prasso_app#12]
It looks like the emails aren't setup from prasso site ( invenbin )
this is the log

[2022-01-16 23:48:27] production.INFO: inviting the user
[2022-01-16 23:48:27] production.ERROR: Expected response code 250 but got code "530", with message "530 Authentication required
" {"userId":1,"exception":"[object] (Swift_TransportException(code: 530): Expected response code 250 but got code \"530\", with message \"530 Authentication required
\" at /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:459)
[stacktrace]
#0 /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(344): Swift_Transport_AbstractSmtpTransport->assertResponseCode()
#1 /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(305): Swift_Transport_AbstractSmtpTransport->executeCommand()
#2 /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(386): Swift_Transport_EsmtpTransport->executeCommand()
#3 /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(485): Swift_Transport_EsmtpTransport->doMailFromCommand()
#4 /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(518): Swift_Transport_AbstractSmtpTransport->doMailTransaction()
#5 /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(206): Swift_Transport_AbstractSmtpTransport->sendTo()
#6 /var/www/html/prasso_api/vendor/swiftmailer/swiftmailer/li

**Comment by bperreault** [comment]
emails work now
